# Generated by Django 4.1.2 on 2022-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
